/**
 * Rules 1 and 2 of the continuity policy, driven through the REAL /api/chat
 * greeting — the surface the student actually lands on.
 *
 *   1. Returning from voice mode continues the chat exactly where it left off.
 *   2. A NEW login does NOT resume the old transcript.
 *
 * The greeting is where both rules are decided: it either replays the existing
 * transcript (`continued: true` plus the messages) or opens a fresh one. The
 * sibling suite (sessionContinuity.test.js) pins the resolvers and the course
 * route; this one pins the branch chat.js actually takes.
 */

jest.mock('../../utils/llmGateway', () => ({
    callLLM: jest.fn().mockResolvedValue({
        choices: [{ message: { content: 'Hey! What are we working on today?' } }],
    }),
    callLLMStream: jest.fn(),
    callLLMStructured: jest.fn().mockResolvedValue({}),
}));

const express = require('express');
const supertest = require('supertest');
const mongoose = require('mongoose');
const { MongoMemoryServer } = require('mongodb-memory-server');

const User = require('../../models/user');
const Conversation = require('../../models/conversation');

const LOGIN_A = 'login-session-aaaa';
const LOGIN_B = 'login-session-bbbb';

let mem;
let app;
let currentUser;
let currentLoginSessionId;

beforeAll(async () => {
    mem = await MongoMemoryServer.create();
    await mongoose.connect(mem.getUri());

    const chatRouter = require('../../routes/chat');
    app = express();
    app.use(express.json());
    app.use((req, _res, next) => {
        req.user = currentUser;
        // What config/middleware.js hands the route: express-session +
        // passport. The marker lives on req.session and is regenerated by
        // passport on every req.logIn, so a new login arrives with a new one.
        req.session = { loginSessionId: currentLoginSessionId };
        req.isAuthenticated = () => true;
        next();
    });
    app.use('/api/chat', chatRouter);
}, 60000);

afterAll(async () => {
    await mongoose.disconnect();
    if (mem) await mem.stop();
});

afterEach(async () => {
    await User.deleteMany({});
    await Conversation.deleteMany({});
});

let seq = 0;
const makeStudent = async () => {
    seq += 1;
    const u = await User.create({
        username: `greeter${seq}`,
        email: `greeter${seq}@example.com`,
        firstName: 'Sam',
        lastName: 'Tester',
        role: 'student',
        selectedTutorId: 'default',
    });
    currentUser = u;
    return u;
};

const greet = () => supertest(app).post('/api/chat').send({ isGreeting: true, skipCourse: true });

describe('Rule 1: returning from voice continues the same chat', () => {
    test('the just-spoken turns come back as the transcript, with no new greeting', async () => {
        const user = await makeStudent();
        // A conversation as voice leaves it: the typed exchange, the voice
        // exchange folded into the SAME document, and the "[Voice session ...]"
        // continuity marker voice writes on the way out.
        const convo = await Conversation.create({
            userId: user._id,
            loginSessionId: LOGIN_A,
            lastActivity: new Date(),
            messages: [
                { role: 'user', content: 'help me with 3x + 6 = 18' },
                { role: 'assistant', content: 'What undoes the +6?' },
                { role: 'user', content: 'subtract six' },
                { role: 'assistant', content: 'Right — so 3x = 12.' },
                { role: 'assistant', content: '[Voice session just ended] recap for the tutor' },
            ],
        });
        user.activeConversationId = convo._id;
        await user.save();

        currentLoginSessionId = LOGIN_A;   // same sign-in — voice never re-authenticates
        const res = await greet();

        expect(res.status).toBe(200);
        expect(res.body.continued).toBe(true);
        expect(String(res.body.conversationId)).toBe(String(convo._id));
        // Exactly where it left off — including the turns spoken in voice mode.
        expect(res.body.messages.map(m => m.content)).toEqual([
            'help me with 3x + 6 = 18',
            'What undoes the +6?',
            'subtract six',
            'Right — so 3x = 12.',
        ]);
        // The "[Voice session ...]" marker is LLM-facing context, never a bubble.
        expect(res.body.text).toBe('');

        // Nothing was appended: no duplicate greeting stacked onto a live thread.
        const after = await Conversation.findById(convo._id);
        expect(after.messages).toHaveLength(5);
    });

    test('a mid-session page reload also continues rather than re-greeting', async () => {
        const user = await makeStudent();
        const convo = await Conversation.create({
            userId: user._id,
            loginSessionId: LOGIN_A,
            lastActivity: new Date(),
            messages: [
                { role: 'assistant', content: 'Hey Sam! What are we working on?' },
                { role: 'user', content: 'fractions' },
                { role: 'assistant', content: 'Nice — try 1/2 + 1/3.' },
            ],
        });
        user.activeConversationId = convo._id;
        await user.save();

        currentLoginSessionId = LOGIN_A;
        const res = await greet();

        expect(res.body.continued).toBe(true);
        expect(res.body.messages).toHaveLength(3);
        expect(await Conversation.countDocuments({ userId: user._id })).toBe(1);
    });
});

describe('Rule 2: a new login does not resume the old transcript', () => {
    test('a fresh sign-in gets a new conversation, not the previous one', async () => {
        const user = await makeStudent();
        const previous = await Conversation.create({
            userId: user._id,
            loginSessionId: LOGIN_A,
            // Seconds old: the 30-minute idle window would happily reuse this.
            // Only the login marker distinguishes it.
            lastActivity: new Date(),
            messages: [
                { role: 'user', content: 'last session I was stuck on slope' },
                { role: 'assistant', content: 'Rise over run — remember?' },
            ],
        });
        user.activeConversationId = previous._id;
        await user.save();

        currentLoginSessionId = LOGIN_B;
        const res = await greet();

        expect(res.status).toBe(200);
        // Not a continuation, and none of the old turns are handed back.
        expect(res.body.continued).toBeFalsy();
        const returnedContents = (res.body.messages || []).map(m => m.content);
        expect(returnedContents).not.toContain('last session I was stuck on slope');
        expect(returnedContents).not.toContain('Rise over run — remember?');

        // The student is pointed at a brand-new conversation stamped with THIS
        // login; the old transcript is left intact, not extended.
        const reloadedUser = await User.findById(user._id);
        expect(String(reloadedUser.activeConversationId)).not.toBe(String(previous._id));
        const fresh = await Conversation.findById(reloadedUser.activeConversationId);
        expect(fresh.loginSessionId).toBe(LOGIN_B);
        expect(fresh.messages.some(m => m.content.includes('slope'))).toBe(false);

        const old = await Conversation.findById(previous._id);
        expect(old.messages).toHaveLength(2);
    });

    test('an unmarked legacy conversation is adopted once, then rolls on the next login', async () => {
        // Deploy day: nothing has a marker. Rolling everything would cut live
        // sessions, so the first login claims instead — and the login after
        // that behaves exactly like the test above.
        const user = await makeStudent();
        const legacy = await Conversation.create({
            userId: user._id,
            lastActivity: new Date(),
            messages: [
                { role: 'user', content: 'written before the marker existed' },
                { role: 'assistant', content: 'and answered before it too' },
            ],
        });
        user.activeConversationId = legacy._id;
        await user.save();

        currentLoginSessionId = LOGIN_A;
        const adopted = await greet();
        expect(adopted.body.continued).toBe(true);
        expect(String(adopted.body.conversationId)).toBe(String(legacy._id));
        expect((await Conversation.findById(legacy._id)).loginSessionId).toBe(LOGIN_A);

        currentUser = await User.findById(user._id);
        currentLoginSessionId = LOGIN_B;
        const rolled = await greet();
        expect(rolled.body.continued).toBeFalsy();
        expect(String((await User.findById(user._id)).activeConversationId))
            .not.toBe(String(legacy._id));
    });
});
