/**
 * Problem Tracking — stable IDs and 7-day "recently shown" dedup.
 *
 * Two problem sources need deduplication:
 *  - 'generator': template-driven problems from utils/problemGenerator.js
 *    (used by screener, badge launch, mastery phase, etc.)
 *  - 'ai-text': problems generated by Maya in her LLM response and detected
 *    post-hoc by processMathMessage (warmups, lesson teach turns, etc.)
 *
 * Both flow into user.recentProblems, keyed by a canonical content hash so
 * the same problem in different sources still collides. See
 * [[mathmatix-problem-tracking]] for the design rationale.
 *
 * @module utils/problemTracking
 */

const crypto = require('crypto');

const DEFAULT_WINDOW_DAYS = 7;
const MAX_HISTORY = 500;
const SNIPPET_MAX_CHARS = 200;

/**
 * Compute a stable, content-derived ID for a problem. The same problem
 * (same skill + same content + same answer, post-normalization) always
 * produces the same ID — which is what makes dedup work across template
 * regenerations and across the generator/ai-text divide.
 *
 * @param {Object} params
 * @param {string} params.skillId
 * @param {string} params.content - The problem text shown to the student
 * @param {string|number} [params.answer] - The expected answer, if known
 * @returns {string} 16-char hex hash
 */
function canonicalProblemId({ skillId, content, answer }) {
  const norm = `${(skillId || '').trim().toLowerCase()}|${normalizeContent(content)}|${normalizeAnswer(answer)}`;
  return crypto.createHash('sha256').update(norm).digest('hex').slice(0, 16);
}

/**
 * Hash the problem content alone (no skillId, no answer) — useful when
 * checking if "this exact problem text" has been shown before regardless
 * of what the system thinks the skill/answer is.
 */
function contentHash(content) {
  return crypto.createHash('sha256').update(normalizeContent(content)).digest('hex').slice(0, 16);
}

/**
 * Strip whitespace + lowercase, so cosmetic differences ("2+3" vs "2 + 3"
 * vs "  2+3 ") don't make the same problem look different.
 */
function normalizeContent(content) {
  if (!content) return '';
  return String(content).replace(/\s+/g, '').toLowerCase();
}

function normalizeAnswer(answer) {
  if (answer === undefined || answer === null) return '';
  if (typeof answer === 'object') {
    try { return JSON.stringify(answer); } catch (_) { return ''; }
  }
  return String(answer).replace(/\s+/g, '').toLowerCase();
}

/**
 * Record that a problem was shown to a user. Mutates user.recentProblems
 * in place and caps to MAX_HISTORY entries. Caller is responsible for
 * user.save() and user.markModified('recentProblems').
 *
 * @param {Object} user - Mongoose user document
 * @param {Object} entry
 * @param {string} entry.problemId - Canonical or generator-emitted ID
 * @param {string} entry.skillId
 * @param {'generator'|'ai-text'} entry.source
 * @param {string} [entry.contentHash] - Pure-content hash for cross-source matching
 */
function recordShownProblem(user, { problemId, skillId, source, contentHash: ch, content }) {
  if (!user || !problemId) return;
  if (!user.recentProblems) user.recentProblems = [];

  user.recentProblems.push({
    problemId,
    skillId: skillId || null,
    source,
    contentHash: ch || null,
    contentSnippet: content ? String(content).trim().slice(0, SNIPPET_MAX_CHARS) : null,
    shownAt: new Date(),
  });

  if (user.recentProblems.length > MAX_HISTORY) {
    user.recentProblems = user.recentProblems.slice(-MAX_HISTORY);
  }
}

/**
 * Has this problem been shown to this user within the window?
 * Matches by problemId OR contentHash (so a 'generator' entry and a
 * later 'ai-text' entry with the same content collide).
 *
 * @param {Object} user
 * @param {Object} candidate - { problemId, contentHash? }
 * @param {number} [withinDays=7]
 * @returns {boolean}
 */
function wasRecentlyShown(user, candidate, withinDays = DEFAULT_WINDOW_DAYS) {
  if (!user?.recentProblems?.length) return false;
  if (!candidate?.problemId && !candidate?.contentHash) return false;

  const cutoff = Date.now() - withinDays * 24 * 60 * 60 * 1000;

  for (const entry of user.recentProblems) {
    const ts = entry.shownAt ? new Date(entry.shownAt).getTime() : 0;
    if (ts < cutoff) continue;
    if (candidate.problemId && entry.problemId === candidate.problemId) return true;
    if (candidate.contentHash && entry.contentHash && entry.contentHash === candidate.contentHash) return true;
  }
  return false;
}

/**
 * All problemIds shown to the user in the window — for prompt injection
 * ("don't reuse these problems"). Optionally filtered by source/skillId.
 *
 * @param {Object} user
 * @param {Object} [opts]
 * @param {number} [opts.withinDays=7]
 * @param {'generator'|'ai-text'} [opts.source]
 * @param {string} [opts.skillId]
 * @returns {Array<{problemId: string, contentHash: string|null, skillId: string|null, shownAt: Date}>}
 */
function getRecentlyShown(user, opts = {}) {
  const { withinDays = DEFAULT_WINDOW_DAYS, source, skillId } = opts;
  if (!user?.recentProblems?.length) return [];

  const cutoff = Date.now() - withinDays * 24 * 60 * 60 * 1000;

  return user.recentProblems.filter(entry => {
    const ts = entry.shownAt ? new Date(entry.shownAt).getTime() : 0;
    if (ts < cutoff) return false;
    if (source && entry.source !== source) return false;
    if (skillId && entry.skillId !== skillId) return false;
    return true;
  });
}

module.exports = {
  canonicalProblemId,
  contentHash,
  recordShownProblem,
  wasRecentlyShown,
  getRecentlyShown,
  MAX_HISTORY,
  DEFAULT_WINDOW_DAYS,
  SNIPPET_MAX_CHARS,
};
