// scripts/seedUnifiedSkills.js
// Seeds the unified "Map of Mathmatix" taxonomy skills
// (seeds/skills-unified.json, generated by scripts/genUnifiedSkills.py) into the
// Skill collection. Non-destructive upsert — these coexist with the existing
// per-course catalog until items are migrated to the unified skill ids.
//
// Usage:
//   node scripts/seedUnifiedSkills.js            # upsert
//   node scripts/seedUnifiedSkills.js --fresh    # clear prior unified skills first
//
// Regenerate the JSON first if the taxonomy changed:
//   python3 scripts/genUnifiedSkills.py

require('dotenv').config();
const fs = require('fs');
const path = require('path');
const mongoose = require('mongoose');

const FILE = path.join(__dirname, '..', 'seeds', 'skills-unified.json');

async function main() {
  if (!process.env.MONGO_URI) { console.error('MONGO_URI not set.'); process.exit(1); }
  if (!fs.existsSync(FILE)) {
    console.error(`Missing ${path.relative(process.cwd(), FILE)} — run: python3 scripts/genUnifiedSkills.py`);
    process.exit(1);
  }
  const skills = JSON.parse(fs.readFileSync(FILE, 'utf8'));
  const fresh = process.argv.includes('--fresh');

  await mongoose.connect(process.env.MONGO_URI);
  const Skill = require('../models/skill');

  if (fresh) {
    const del = await Skill.deleteMany({ source: 'unified-taxonomy' });
    console.log(`Cleared ${del.deletedCount} prior unified skills (--fresh).`);
  }

  let up = 0;
  for (const s of skills) {
    await Skill.updateOne(
      { skillId: s.skillId },
      {
        $set: s,
        // GET /api/mastery/map queries { isActive: true, source: 'unified-taxonomy' }
        // and returns `seeded: false` when that finds nothing — the whole skill
        // map goes dark. skills-unified.json does not carry isActive, so on
        // insert it depends entirely on setDefaultsOnInsert; pinning it here
        // means the map cannot hinge on that behaviour staying default-on.
        //
        // $setOnInsert, not $set: re-running this must never re-activate a
        // skill somebody deliberately turned off.
        $setOnInsert: { isActive: true },
      },
      { upsert: true }
    );
    up += 1;
  }
  console.log(`Upserted ${up} unified taxonomy skills into MongoDB (source: unified-taxonomy).`);

  // Say plainly whether the map will actually render, since "Upserted 349" and
  // "the map works" are not the same claim.
  const live = await Skill.countDocuments({ isActive: true, source: 'unified-taxonomy' });
  console.log(`Visible to GET /api/mastery/map: ${live} skills.`);
  if (!live) console.warn('WARNING: map will still report seeded:false.');

  await mongoose.disconnect();
  process.exit(0);
}

main().catch(async (err) => {
  console.error('seedUnifiedSkills failed:', err.message);
  try { await mongoose.disconnect(); } catch { /* noop */ }
  process.exit(1);
});
