/**
 * EVERY COURSE'S CONTENT MUST ACTUALLY REACH THE TUTOR.
 *
 * The module banks were generated by several scripts over time and they do not
 * agree on field names. The prompt builders read one name per field and
 * interpolated it raw, so a bank that picked the other name produced a prompt
 * line reading literally "Answer: undefined" — or, for an I-do step, no worked
 * examples at all. Nothing failed. The lesson just quietly had no content, and
 * the tutor improvised over the hole.
 *
 * Found by auditing all 15 pathways after the Financial Literacy report:
 *   • geometry 3d_geometry — 9 worked solutions stored under `explanation`,
 *     every one rendered as "Solution: undefined"
 *   • 6th-grade-math and early-math-foundations `final_review` — 10 I-do steps
 *     whose worked examples live under `problems`, so `step.examples` was empty
 *     and the tutor was told to "walk through the examples" with none listed
 *   • 27 guided-practice steps across geometry / grade-8-math / algebra-1 /
 *     precalculus using `solution`+`hint`, printing "Answer: undefined"
 *
 * This renders EVERY module × EVERY scaffold step of EVERY pathway through the
 * real builder — the same call routes/chat.js makes — and fails on either
 * failure mode. It is a data test as much as a code test: a newly generated bank
 * that invents another field name fails here instead of shipping a silent hole.
 */

const fs = require('fs');
const path = require('path');
const { buildCourseSystemPrompt } = require('../../utils/coursePrompt');
const TUTOR_CONFIG = require('../../utils/tutorConfig');

const ROOT = path.join(__dirname, '../..');
const RESOURCES = path.join(ROOT, 'public/resources');
const PUBLIC = path.join(ROOT, 'public');
const tutorProfile = TUTOR_CONFIG.default || Object.values(TUTOR_CONFIG)[0];

// Lines the builders produce by interpolating one field. If that field is missing
// under the name being read, the line reads "…: undefined" — a hole where the
// answer key, the worked solution, or the problem itself should be.
const BROKEN_LINE =
  /^\s*(?:Problem|Example)\s+\d+:\s*(?:undefined|null)\s*$|^\s*(?:Answer|Solution):\s*(?:undefined|null)\s*$|^\s*(?:Hints[^:]*|Gentle hints):\s*(?:undefined|null)\s*$/;

const pathwayFiles = fs.readdirSync(RESOURCES).filter((f) => f.endsWith('-pathway.json'));

/** Every (course, module, stepIndex) a student can actually sit in. */
function everyTeachingStep() {
  const out = [];
  for (const file of pathwayFiles) {
    const pathway = JSON.parse(fs.readFileSync(path.join(RESOURCES, file), 'utf8'));
    const courseId = pathway.courseId || file.replace('-pathway.json', '');
    const sessionModules = (pathway.modules || []).map((m, i) => ({
      moduleId: m.moduleId, unit: m.unit, title: m.title,
      status: i === 0 ? 'in_progress' : 'locked',
    }));
    for (const currentModule of pathway.modules || []) {
      if (!currentModule.moduleFile) continue;
      const modulePath = path.join(PUBLIC, currentModule.moduleFile);
      if (!fs.existsSync(modulePath)) continue;
      const scaffoldData = JSON.parse(fs.readFileSync(modulePath, 'utf8'));
      // Checkpoints take the assessment prompt, which lists problems from a
      // different field entirely — covered by its own expectations below.
      const isCheckpoint = scaffoldData.type === 'assessment'
        || scaffoldData.diagnosticMode || currentModule.isCheckpoint;
      if (isCheckpoint) continue;
      (scaffoldData.scaffold || []).forEach((step, index) => {
        out.push({ courseId, pathway, currentModule, scaffoldData, step, index, sessionModules });
      });
    }
  }
  return out;
}

function render(c) {
  return buildCourseSystemPrompt({
    userProfile: { firstName: 'Sam', gradeLevel: '9' },
    tutorProfile,
    courseSession: {
      courseId: c.courseId,
      courseName: c.pathway.track,
      currentModuleId: c.currentModule.moduleId,
      currentScaffoldIndex: c.index,
      overallProgress: 0,
      modules: c.sessionModules,
    },
    pathway: c.pathway,
    scaffoldData: c.scaffoldData,
    currentModule: c.currentModule,
  });
}

const STEPS = everyTeachingStep();

describe('every course renders', () => {
  test('the audit actually covers every pathway on disk', () => {
    expect(pathwayFiles.length).toBeGreaterThanOrEqual(15);
    const covered = new Set(STEPS.map((s) => s.courseId));
    // Only the parent guides are small; every student course must contribute.
    expect(covered.size).toBe(pathwayFiles.length);
    expect(STEPS.length).toBeGreaterThan(1000);
  });

  test('no step renders a line ending in "undefined"', () => {
    const broken = [];
    for (const c of STEPS) {
      const prompt = render(c);
      const at = prompt.indexOf('▶ CURRENT STEP');
      if (at === -1) continue;
      prompt.slice(at).split('\n').forEach((line) => {
        if (BROKEN_LINE.test(line)) {
          broken.push(`${c.courseId}/${c.currentModule.moduleId}[${c.index}] (${c.step.type}) → ${line.trim()}`);
        }
      });
    }
    expect(broken).toEqual([]);
  });

  test('every step produces a CURRENT STEP block the tutor can teach from', () => {
    const empty = [];
    for (const c of STEPS) {
      const prompt = render(c);
      const at = prompt.indexOf('▶ CURRENT STEP');
      if (at === -1) { empty.push(`${c.courseId}/${c.currentModule.moduleId}[${c.index}] — no step block`); continue; }
      if (!c.step.title) empty.push(`${c.courseId}/${c.currentModule.moduleId}[${c.index}] — step has no title`);
    }
    expect(empty).toEqual([]);
  });
});

describe('the teaching payload is present, not just the instructions', () => {
  // A `model` step whose examples are invisible still emits the whole "walk
  // through the examples" block — the failure only shows as a tutor with nothing
  // to model. Assert the content itself made it into the prompt.
  test('every I-do step puts at least one worked example in the prompt', () => {
    const bare = [];
    for (const c of STEPS.filter((s) => s.step.type === 'model')) {
      const prompt = render(c);
      const at = prompt.indexOf('▶ CURRENT STEP');
      if (!/\nExample 1: \S/.test(prompt.slice(at))) {
        bare.push(`${c.courseId}/${c.currentModule.moduleId}[${c.index}] "${c.step.title}" — keys=${Object.keys(c.step)}`);
      }
    }
    expect(bare).toEqual([]);
  });

  test('every practice step puts at least one problem in the prompt', () => {
    const bare = [];
    const practice = STEPS.filter((s) => s.step.type === 'guided_practice' || s.step.type === 'independent_practice');
    for (const c of practice) {
      const prompt = render(c);
      const at = prompt.indexOf('▶ CURRENT STEP');
      const marker = c.pathway.audience === 'parent' ? /\n\s+Example 1: \S/ : /\n\s+Problem 1: \S/;
      if (!marker.test(prompt.slice(at))) {
        bare.push(`${c.courseId}/${c.currentModule.moduleId}[${c.index}] "${c.step.title}" — keys=${Object.keys(c.step)}`);
      }
    }
    expect(bare).toEqual([]);
  });

  // The builders now DROP a line whose field is missing rather than printing
  // "undefined", which is right for the prompt and wrong for a test that only
  // looks for the word. So assert the stronger thing: an answer key that exists
  // in the data must reach the tutor. Losing an alias silently would otherwise
  // read as a clean prompt with the answer key quietly gone — the exact shape of
  // the bug this file exists to catch.
  const ANSWER_KEYS = ['answer', 'solution', 'explanation'];
  const hasAnswer = (item) => ANSWER_KEYS.some((k) => item[k] !== undefined && item[k] !== null && item[k] !== '');
  const hasText = (item) => !!(item.problem || item.question);

  test('every answer key present in the data reaches the prompt', () => {
    const lost = [];
    for (const c of STEPS) {
      const { step } = c;
      let items = [];
      if (step.type === 'model') {
        items = (step.examples && step.examples.length) ? step.examples : (step.problems || []);
      } else if (step.type === 'guided_practice' || step.type === 'independent_practice') {
        items = step.problems || [];
      }
      if (!Array.isArray(items)) items = [];
      const expected = items.filter((it) => hasText(it) && hasAnswer(it)).length;
      if (!expected) continue;
      const prompt = render(c);
      const block = prompt.slice(prompt.indexOf('▶ CURRENT STEP'));
      const label = step.type === 'model' ? /^\s*Solution:\s*\S/ : /^\s*Answer:\s*\S/;
      const got = block.split('\n').filter((l) => label.test(l)).length;
      if (got < expected) {
        lost.push(`${c.courseId}/${c.currentModule.moduleId}[${c.index}] (${step.type}) — ${expected} in data, ${got} in prompt`);
      }
    }
    expect(lost).toEqual([]);
  });

  test('every hint present in the data reaches the prompt', () => {
    const lost = [];
    const practice = STEPS.filter((s) => s.step.type === 'guided_practice' || s.step.type === 'independent_practice');
    for (const c of practice) {
      const withHints = (c.step.problems || []).filter(
        (p) => hasText(p) && ((Array.isArray(p.hints) && p.hints.length) || p.hint));
      if (!withHints.length) continue;
      const block = render(c).slice(render(c).indexOf('▶ CURRENT STEP'));
      const got = block.split('\n').filter((l) => /^\s*(?:Hints[^:]*|Gentle hints):\s*\S/.test(l)).length;
      if (got < withHints.length) {
        lost.push(`${c.courseId}/${c.currentModule.moduleId}[${c.index}] — ${withHints.length} hinted problems, ${got} hint lines`);
      }
    }
    expect(lost).toEqual([]);
  });

  test('every concept-intro step puts its source material in the prompt', () => {
    const bare = [];
    for (const c of STEPS.filter((s) => s.step.type === 'explanation')) {
      const body = (c.pathway.audience === 'parent' ? c.step.text : (c.step.content || c.step.text)) || '';
      if (!String(body).trim()) {
        bare.push(`${c.courseId}/${c.currentModule.moduleId}[${c.index}] "${c.step.title}" — keys=${Object.keys(c.step)}`);
      }
    }
    expect(bare).toEqual([]);
  });
});

describe('the field-name readers', () => {
  // These are what make the above hold. Pinned directly so a future refactor that
  // drops an alias fails here with a clear cause instead of in the sweep above.
  const src = fs.readFileSync(path.join(ROOT, 'utils/coursePrompt.js'), 'utf8');

  test('worked examples are read from `examples` OR `problems`', () => {
    expect(src).toMatch(/function stepExamples\(step\)/);
    expect(src).toMatch(/step\.examples && step\.examples\.length\) \? step\.examples : step\.problems/);
  });

  test('an answer may be `answer`, `solution` or `explanation`', () => {
    expect(src).toMatch(/function itemAnswer\(item\)/);
    ['item.answer', 'item.solution', 'item.explanation'].forEach((k) => expect(src).toContain(k));
  });

  test('hints may be a list or a single `hint`', () => {
    expect(src).toMatch(/function itemHints\(item\)/);
    expect(src).toMatch(/if \(item\.hint\) return \[item\.hint\]/);
  });

  test('problem text may be `problem` or `question`', () => {
    expect(src).toMatch(/function itemText\(item\)/);
    expect(src).toMatch(/item\.problem \|\| item\.question/);
  });
});
