/**
 * Integrity of the unified "Map of Mathmatix" skill graph.
 *
 * The graph is the substrate for prerequisite closure, unlock cascades and the
 * strand progress board, so a bad edge is not a cosmetic problem — it either
 * locks a student out of work they are ready for, or clears a skill they never
 * demonstrated. These tests are the guard on seeds/skills-unified.json, which is
 * generated by scripts/genUnifiedSkills.py from the taxonomy.
 */

const fs = require('fs');
const path = require('path');

const SKILLS = JSON.parse(
  fs.readFileSync(path.join(__dirname, '../../seeds/skills-unified.json'), 'utf8')
);

// Ascending order of abstraction. A cross-level prerequisite must point strictly
// downward in this list — that is what makes a strand readable as one through-line.
const COURSE_ORDER = ['ELEM', 'MS', 'ALG1', 'GEO', 'ALG2', 'PREC', 'CALC'];
const STRANDS = ['QNT', 'PRP', 'EQV', 'FNC', 'SPC', 'DTA'];

const byId = new Map(SKILLS.map((s) => [s.skillId, s]));
const edgesOf = (s) => [...(s.prerequisites || []), ...(s.crossPrereqs || [])];
const rank = (id) => COURSE_ORDER.indexOf(byId.get(id).courseLevel);

describe('unified skill graph', () => {
  test('every skill has a well-formed id, strand and course level', () => {
    const bad = SKILLS.filter(
      (s) =>
        !/^[A-Z0-9]+\.[A-Z]{3}\.\d+$/.test(s.skillId) ||
        !STRANDS.includes(s.strand) ||
        !COURSE_ORDER.includes(s.courseLevel)
    );
    expect(bad.map((s) => s.skillId)).toEqual([]);
  });

  test('skill ids are unique', () => {
    expect(byId.size).toBe(SKILLS.length);
  });

  test('every prerequisite reference resolves to a real skill', () => {
    const dangling = [];
    SKILLS.forEach((s) => {
      edgesOf(s).forEach((p) => {
        if (!byId.has(p)) dangling.push(`${s.skillId} -> ${p}`);
      });
    });
    expect(dangling).toEqual([]);
  });

  test('the prerequisite graph is acyclic', () => {
    // Iterative DFS with colouring; reports the actual cycle rather than just failing.
    const WHITE = 0;
    const GREY = 1;
    const BLACK = 2;
    const colour = new Map(SKILLS.map((s) => [s.skillId, WHITE]));
    const cycles = [];

    const visit = (start) => {
      const stack = [[start, 0]];
      const trail = [];
      colour.set(start, GREY);
      trail.push(start);
      while (stack.length) {
        const frame = stack[stack.length - 1];
        const kids = edgesOf(byId.get(frame[0]));
        if (frame[1] >= kids.length) {
          colour.set(frame[0], BLACK);
          stack.pop();
          trail.pop();
          continue;
        }
        const next = kids[frame[1]++];
        if (!byId.has(next)) continue;
        if (colour.get(next) === GREY) {
          cycles.push([...trail.slice(trail.indexOf(next)), next].join(' -> '));
          continue;
        }
        if (colour.get(next) === WHITE) {
          colour.set(next, GREY);
          trail.push(next);
          stack.push([next, 0]);
        }
      }
    };

    SKILLS.forEach((s) => {
      if (colour.get(s.skillId) === WHITE) visit(s.skillId);
    });
    expect(cycles).toEqual([]);
  });

  test('a skill is never its own prerequisite', () => {
    const selfRefs = SKILLS.filter((s) => edgesOf(s).includes(s.skillId));
    expect(selfRefs.map((s) => s.skillId)).toEqual([]);
  });

  test('same-level prerequisites never point upward in course level', () => {
    const upward = [];
    SKILLS.forEach((s) => {
      (s.prerequisites || []).forEach((p) => {
        if (byId.has(p) && rank(p) > rank(s.skillId)) {
          upward.push(`${s.skillId} (${s.courseLevel}) <- ${p} (${byId.get(p).courseLevel})`);
        }
      });
    });
    expect(upward).toEqual([]);
  });

  test('cross-level prerequisites point strictly downward', () => {
    const wrong = [];
    SKILLS.forEach((s) => {
      (s.crossPrereqs || []).forEach((p) => {
        if (byId.has(p) && rank(p) >= rank(s.skillId)) {
          wrong.push(`${s.skillId} (${s.courseLevel}) <- ${p} (${byId.get(p).courseLevel})`);
        }
      });
    });
    expect(wrong).toEqual([]);
  });

  test('prerequisites and crossPrereqs do not overlap', () => {
    const dupes = SKILLS.filter((s) =>
      (s.crossPrereqs || []).some((p) => (s.prerequisites || []).includes(p))
    );
    expect(dupes.map((s) => s.skillId)).toEqual([]);
  });

  test('enables is the exact reverse of the prerequisite edges', () => {
    const expected = new Map(SKILLS.map((s) => [s.skillId, new Set()]));
    SKILLS.forEach((s) => {
      edgesOf(s).forEach((p) => {
        if (expected.has(p)) expected.get(p).add(s.skillId);
      });
    });
    const mismatched = SKILLS.filter((s) => {
      const want = expected.get(s.skillId);
      const got = new Set(s.enables || []);
      return want.size !== got.size || [...want].some((id) => !got.has(id));
    });
    expect(mismatched.map((s) => s.skillId)).toEqual([]);
  });

  test('every course level has an entry point reachable without prerequisites', () => {
    // Otherwise a student placed at that level has nothing they can legally start.
    const stranded = COURSE_ORDER.filter(
      (lvl) =>
        SKILLS.some((s) => s.courseLevel === lvl) &&
        !SKILLS.some((s) => s.courseLevel === lvl && edgesOf(s).length === 0)
    );
    // ELEM is the only level expected to be self-rooting; every other level may
    // legitimately reach down, so we only assert the graph as a whole has roots.
    expect(SKILLS.filter((s) => edgesOf(s).length === 0).length).toBeGreaterThan(0);
    expect(stranded).not.toContain('ELEM');
  });

  test('no skill is unreachable from the roots', () => {
    const roots = SKILLS.filter((s) => edgesOf(s).length === 0).map((s) => s.skillId);
    const seen = new Set(roots);
    const queue = [...roots];
    while (queue.length) {
      const id = queue.shift();
      (byId.get(id).enables || []).forEach((next) => {
        if (!seen.has(next)) {
          seen.add(next);
          queue.push(next);
        }
      });
    }
    const orphans = SKILLS.filter((s) => !seen.has(s.skillId)).map((s) => s.skillId);
    expect(orphans).toEqual([]);
  });

  test('every skill has a student-facing label', () => {
    const missing = SKILLS.filter((s) => !s.studentLabel || !s.studentLabel.trim());
    expect(missing.map((s) => s.skillId)).toEqual([]);
  });

  test('student labels are short enough to read on a board', () => {
    const wordy = SKILLS.filter((s) => s.studentLabel.split(/\s+/).length > 8);
    expect(wordy.map((s) => `${s.skillId}: ${s.studentLabel}`)).toEqual([]);
  });

  test('student labels are distinct within a strand', () => {
    const collisions = [];
    STRANDS.forEach((strand) => {
      const seen = new Map();
      SKILLS.filter((s) => s.strand === strand).forEach((s) => {
        const key = s.studentLabel.toLowerCase();
        if (seen.has(key)) collisions.push(`${strand}: ${seen.get(key)} / ${s.skillId} both "${s.studentLabel}"`);
        seen.set(key, s.skillId);
      });
    });
    expect(collisions).toEqual([]);
  });

  test('student labels avoid the filler the formal names lean on', () => {
    // "...concepts", "...basics", "properties of X" are category nouns; the label
    // is supposed to name what the student does.
    const filler = /\b(concepts|basics)\s*$|^properties of\b/i;
    const offenders = SKILLS.filter((s) => filler.test(s.studentLabel));
    expect(offenders.map((s) => `${s.skillId}: ${s.studentLabel}`)).toEqual([]);
  });

  test('standards codes are well formed', () => {
    // Bare CCSS-M codes are self-identifying; anything outside CCSS must carry a
    // framework prefix so a reader never has to guess which system a code is in.
    const ccss = /^(K|[1-8]|HS[A-Z]{1,2})[.-][A-Z]{1,3}(\.[A-Z])?(\.\d+[a-z]?)?(\.[a-z])?$/;
    const prefixed = /^(AP-CALC|AP-PRECALC|AP-STATS|OH):[\w.-]+$/;
    const malformed = [];
    SKILLS.forEach((s) => {
      (s.standardsAlignment || []).forEach((c) => {
        if (!ccss.test(c) && !prefixed.test(c)) malformed.push(`${s.skillId}: ${c}`);
      });
    });
    expect(malformed).toEqual([]);
  });

  test('only the skills CCSS genuinely does not cover lack an alignment', () => {
    // These were marked `no-ccss` by the audit with a stated reason rather than
    // force-fitting a code. The Geometry logic unit (laws of detachment and
    // syllogism) is the clearest case: CCSS omits it, and Ohio follows CCSS.
    const EXPECTED_NO_CCSS = [
      'ELEM.DTA.3',   // line graphs — no CCSS anchor
      'ELEM.DTA.4',   // likelihood — CCSS has no probability before 7.SP.C.5
      'GEO.DTA.4',    // geometric probability
      'GEO.EQV.1',    // logic: conditional statements
      'GEO.EQV.2',    // logic: detachment and syllogism
      'PREC.FNC.14',  // parametric curves — AP Precalculus, outside CCSS
      'PREC.FNC.15'   // polar graphs — AP Precalculus, outside CCSS
    ];
    const unaligned = SKILLS.filter((s) => !(s.standardsAlignment || []).length).map((s) => s.skillId);
    expect(unaligned.sort()).toEqual(expect.arrayContaining([]));
    unaligned.forEach((id) => expect(EXPECTED_NO_CCSS).toContain(id));
  });

  test('every CCSS code cited resolves to real standard text', () => {
    // The whole point of the audit is that a code is traceable. A code we cannot
    // look up is indistinguishable from one that was invented.
    const ccssRef = JSON.parse(
      fs.readFileSync(path.join(__dirname, '../../seeds/unified-taxonomy/ccss-reference.json'), 'utf8')
    );
    const isCcss = /^(K|[1-8]|HS[A-Z]{1,2})[.-]/;
    const unresolved = [];
    SKILLS.forEach((s) => {
      (s.standardsAlignment || []).forEach((c) => {
        if (!isCcss.test(c)) return;              // AP/Ohio codes are not in this reference
        const parent = c.replace(/\.[a-z]$/, ''); // sub-part text lives under its parent
        if (!ccssRef[c] && !ccssRef[parent]) unresolved.push(`${s.skillId}: ${c}`);
      });
    });
    expect(unresolved).toEqual([]);
  });

  test('a grade-band code is never attached to a skill levels away from it', () => {
    // A K-8 code on a calculus skill means the alignment was guessed.
    const LEVEL_FLOOR = { ELEM: 0, MS: 5, ALG1: 7, GEO: 7, ALG2: 8, PREC: 8, CALC: 9 };
    const gradeOf = (code) => {
      const m = /^([K1-8])[.-]/.exec(code);
      if (!m) return null;              // HS or prefixed — no numeric grade
      return m[1] === 'K' ? 0 : Number(m[1]);
    };
    const suspicious = [];
    SKILLS.forEach((s) => {
      (s.standardsAlignment || []).forEach((c) => {
        const g = gradeOf(c);
        if (g === null) return;
        // A cross-level prerequisite legitimately reaches down, but the skill's
        // OWN alignment should not sit more than a band below its level.
        if (g < LEVEL_FLOOR[s.courseLevel] - 3) suspicious.push(`${s.skillId} (${s.courseLevel}) <- ${c}`);
      });
    });
    expect(suspicious).toEqual([]);
  });

  test('prerequisite depth stays within a teachable chain length', () => {
    // A smoke alarm on graph shape, not a pedagogical limit. The genuine deepest
    // chain is 23 hops: ELEM.QNT.4 (times tables, grade 3) up through combining
    // like terms, polynomials, factoring and transformations to CALC.FNC.28
    // (separable differential equations). That length is real and load-bearing —
    // it is what lets a calculus failure bridge back to the actual gap.
    //
    // It was 22 before the audit fixes, but by a partly bogus route: adding
    // polynomials hung off GCF/LCM rather than off combining like terms. The
    // chain is now both longer and correct. A jump well past this means a bad edge.
    const depth = new Map();
    const compute = (id) => {
      if (depth.has(id)) return depth.get(id);
      depth.set(id, 0); // cycle guard; acyclicity is asserted separately
      const kids = edgesOf(byId.get(id)).filter((p) => byId.has(p));
      const d = kids.length ? 1 + Math.max(...kids.map(compute)) : 0;
      depth.set(id, d);
      return d;
    };
    SKILLS.forEach((s) => compute(s.skillId));
    const deepest = Math.max(...depth.values());
    expect(deepest).toBeLessThanOrEqual(25);
  });
});
