// models/User.js
const mongoose = require('mongoose');

const messageSchema = new mongoose.Schema({
  role: String,
  content: String
}, { _id: false });

const sessionSchema = new mongoose.Schema({
  date: { type: Date, default: Date.now },
  messages: [messageSchema],
  summary: String,
  activeMinutes: { type: Number, default: 0 }
}, { _id: false });

const userSchema = new mongoose.Schema({
  username: { type: String, unique: true, sparse: true },
  passwordHash: { type: String },
  gradeLevel: { type: String },
  email: { type: String, unique: true, sparse: true },
  googleId: { type: String },
  microsoftId: { type: String },
  firstName: { type: String, required: true },
  lastName: { type: String, required: true },
  name: { type: String, required: false },
  mathCourse: { type: String },
  tonePreference: { type: String },
  learningStyle: { type: String },
  interests: [String],
  createdAt: { type: Date, default: Date.now },
  conversations: [sessionSchema],
  lastLogin: { type: Date, default: Date.now },

  role: { type: String, default: "student" },
  teacherId: { type: mongoose.Schema.Types.ObjectId, ref: 'User', default: null }, // Can be used as parentId for student accounts

  avatar: {
    skin: { type: String, default: 'default' },
    hair: { type: String, default: 'default' },
    top: { type: String, default: 'default' },
    bottom: { type: String, default: 'default' },
    accessory: { type: String, default: 'none' }
  },
  selectedTutorId: { type: String, default: null },

  xp: { type: Number, default: 0 },
  level: { type: Number, default: 1 },
  totalActiveTutoringMinutes: { type: Number, default: 0 },
  weeklyActiveTutoringMinutes: { type: Number, default: 0 },
  lastWeeklyReset: { type: Date, default: Date.now },

  needsProfileCompletion: { type: Boolean, default: false },

  reportFrequency: { type: String, enum: ['weekly', 'biweekly', 'monthly'], default: 'weekly' },
  goalViewPreference: { type: String, enum: ['progress', 'gaps', 'goals'], default: 'progress' },
  parentTone: { type: String, enum: ['casual', 'friendly', 'direct', 'formal'], default: 'friendly' },
  parentLanguage: { type: String, default: 'English' },

  // --- MODIFIED: Renamed and added new invite code fields for clarity ---
  parentToChildInviteCode: { // Code generated by a parent for their child
    code: { type: String, unique: true, sparse: true },
    expiresAt: { type: Date },
    childLinked: { type: Boolean, default: false } // True if a child has used this code
  },
  studentToParentLinkCode: { // Code assigned to a student for their parent to use
    code: { type: String, unique: true, sparse: true },
    parentLinked: { type: Boolean, default: false } // True if a parent has used this code to link
  },
  // --- END MODIFIED ---

  children: [{ // Array of ObjectIds of children linked to this parent (for parent role)
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User'
  }],

  iepPlan: {
    extendedTime: { type: Boolean, default: false },
    simplifiedInstructions: { type: Boolean, default: false },
    frequentCheckIns: { type: Boolean, default: false },
    visualSupport: { type: Boolean, default: false },
    chunking: { type: Boolean, default: false },
    reducedDistraction: { type: Boolean, default: false },
    readingLevel: { type: Number, default: null },
    mathAnxiety: { type: Boolean, default: false },
    preferredScaffolds: [{ type: String }],
    goals: [{
      description: { type: String, required: true },
      targetDate: { type: Date },
      currentProgress: { type: Number, default: 0 },
      measurementMethod: { type: String },
      status: { type: String, default: "active" },
      historicalProgress: [{
        date: { type: Date, default: Date.now },
        value: { type: Number }
      }]
    }]
  }
});

module.exports = mongoose.model('User', userSchema);